name: ApexMuse
favicon: null
layout_spectrum: 0.9092747024260461
typography_spectrum: 0.2567170113325119
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8011896321550012
  lightness: 0.3095788296777755
  saturation: 0.7731605896260589
  rhythmicContrast: 0.9360924460925162
purpose: []
